### ISSUE TITLE
Compiler warning/error for "va_start"

### ISSUE THREAD

**Issue by lendres** [arduino-libraries/Arduino_DebugUtils#12]
There is a compiler warning/error that occurs on build.  It is:
```
...\Arduino_DebugUtils.cpp: In member function 'void Arduino_DebugUtils::print(int, const __FlashStringHelper*, ...)':
...\Arduino_DebugUtils.cpp:86:3: warning: second parameter of 'va_start' not last named argument [-Wvarargs]
va_start(args, fmt_str.c_str());
```

From my investigation, is seems that line 86 (of "Arduino_DebugUtils.cpp") is:
```
va_start(args, fmt_str.c_str());
```
and should instead be:
```
va_start(args, fmt);
```

I'm not overly familiar with that macro, but this version does stop the error and seems to function correctly when I run the examples.

**Comment by aentinger** [comment]
What board are you compiling this for?

**Comment by lendres** [comment]
I've tried a few boards, it does not matter which board it is compiled for.

**Comment by aentinger** [comment]
Let me ask again
>What board are you compiling this for?

As a matter of fact I know that this library works just fine for all `samd` and `mbed` boards.

**Comment by lendres** [comment]
Nano, Uno, Mega.

Yes, it does work, but it also gives a compiler warning.  A good practice is to treat warnings like errors and correct them.

**Comment by lendres** [comment]
> Let me ask again

Also, it's not really necessary to be rude about it.  I responded the way I did because I have tried several boards and suspect that this is related to misuse of a CPP library macro and not related to the particular board.  If you did not try reproducing it, that would be a good place to start.  If you did try to reproduce it and did not get this compiler error, then please let me know and I will assist in reproducing it.

**Comment by per1234** [comment]
You can see warnings from the example sketch compilations for various boards in the CI logs. For example, here is the mentioned warning when compiling for the MKR Zero:
https://github.com/arduino-libraries/Arduino_DebugUtils/runs/2939909649?check_suite_focus=true#step:3:26
