### ISSUE TITLE
Allow getting the debug_level 

### ISSUE THREAD

**Issue by kirk-clendinning** [arduino-libraries/Arduino_DebugUtils#14]
It would be nice for the Debug Utils to be orthogonal so that once a debug level is set, functionality in other parts of the code can be enabled or disabled programmatically.

Add  `int  getDebugMessageLevel(void);` and `int getDebugLevel(void);` to `Arduino_DebugUtils.h`, complimenting the `setDebugMessageLevel()` and `setDebugLevel()` functions.

Add 
```cpp
int getDebugMessageLevel(void) {
  return Debug.getDebugLevel();
}
```
to `Arduino_DebugUtils.cpp`

**Comment by aentinger** [comment]
Hi @kirk-clendinning :wave: Can you please create a PR?

**Comment by kirk-clendinning** [comment]
Alexander,

I have not forgotten you. Just full with programming at work right now, and trying to get an SK6812 lighting project going at home. I will try to find some time do the pull some weekend soon. It’s not much work, I just need to get a few moments. Please keep in touch.

Kind Regards,

-kirk-



It is always easier to criticize than create.
-Clendinning-

Kirk Clendinning
922 Zeek Ridge Ct.
Clermont, Florida 34715-0056
USA

+1 (407) 988-9111

**Comment by aentinger** [comment]
Sure 😉
