### ISSUE TITLE
Adding Debug.info() style functions

### ISSUE THREAD

**Issue by MiheerLele** [arduino-libraries/Arduino_DebugUtils#29]
Hi, has there been any discussion around adding individual functions for each debug logging level, instead of passing in the level explicitly, similar to how the logging module in python works? I believe something like this should work:
```
void Arduino_DebugUtils::info(const char * fmt, ...)
{
  va_list args;
  va_start(args, fmt);
  print(DBG_INFO, fmt, args);
  va_end(args);
}
```
I would be more than happy to open a PR if this feels like something that should be added

**Comment by aentinger** [comment]
Hi @MiheerLele :coffee: :wave: 

This is technically perfectly doable, but would it not add a lot of code duplication? Basically every function would contain the same code, except a different constant as first parameter of `print` :shrug: . What is the advantage of such an API over the existing one from your perspective?

Cheers, Alex

**Comment by MiheerLele** [comment]
Hi Alex,

Agreed, I was just curious to see if you thought one less parameter would be a beneficial tradeoff for the additional API methods

**Comment by aentinger** [comment]
:shrug: It would be simpler. Another alternative would be to provide macros, as done [here](https://github.com/107-systems/107-Arduino-Debug/blob/main/examples/Debug-Basic/Debug-Basic.ino#L34-L38). What do you think? That's the biggest simplification imho.

**Comment by MiheerLele** [comment]
I think thats a good solution 👍
