### ISSUE TITLE
`-Wvla` compiler warnings

### ISSUE THREAD

**Issue by zfields** [arduino-libraries/Arduino_DebugUtils#44]
Running this [**Arduino CLI**](https://arduino.github.io/arduino-cli/latest/) command from the folder of a sketch that `#include`s the "Arduino_DebugUtils" library:

```text
arduino-cli compile --verbose --warnings=all --build-property "build.extra_flags=-Wno-unused-variable -Wno-implicit-fallthrough -Wno-psabi -Wno-deprecated-copy -Wno-missing-field-initializers -Wno-delete-non-virtual-dtor -Wno-sign-compare -Og -g" --fqbn arduino:mbed_opta:opta
```

results in this compiler warning:

```
~/Development/Arduino/libraries/Arduino_DebugUtils/src/Arduino_DebugUtils.cpp: In member function 'void Arduino_DebugUtils::vPrint(const char*, va_list)':
~/Development/Arduino/libraries/Arduino_DebugUtils/src/Arduino_DebugUtils.cpp:139:28: warning: variable length array 'msg_buf' is used [-Wvla]
   char msg_buf[msg_buf_size];
                            ^
```

**Comment by zfields** [comment]
```arduino-cli compile --verbose --warnings=all --build-property "build.extra_flags=-Wno-unused-variable -Wno-implicit-fallthrough -Wno-psabi -Wno-deprecated-copy -Wno-missing-field-initializers -Wno-delete-non-virtual-dtor -Wno-sign-compare -Og -g" --fqbn arduino:mbed_opta:opta <dev folder>```

**Comment by aentinger** [comment]
Variable length arrays are not perfect, but a better solution than dynamic memory allocation on the heap. If you have a sensible design recommendation to eliminate a variable length array in this library (w/o resorting to heap) I'll be happy to review it.

**Comment by zfields** [comment]
I have always used `alloca()` in the past, but I'm not sure if that's available to all embedded platforms.

https://www.man7.org/linux/man-pages/man3/alloca.3.html

**Comment by zfields** [comment]
If `alloca()` is not an option, then it would be good to document `-Wvla` as a required compiler flag.
