### ISSUE TITLE
Option to show debugLevel of each Debug.print() statement (e.g. [V] ...)

### ISSUE THREAD

**Issue by MattStarfield** [arduino-libraries/Arduino_DebugUtils#6]
When looking at a wall of debug print statements, it can be useful to see what debug level each statement was printed at so that you can decide if a particular statement should be moved to a different debug level. This could be achieved with as little as a single character, e.g. DBG_ERROR = E, DBG_WARNING = W, etc...

I suggest adding a switch to include printing the debug level of each Debug.print statement, e.g.

`showDebugLevelOn()`

Debug.print statements could then look like:

`[ timestamp ] [E] "rest of print statement..."`

or

`[ timestamp E ] "rest of print statement..."`

**Comment by aentinger** [comment]
Similar to #7 - Can you please create a PR?

**Comment by aentinger** [comment]
Duplicate of #7.
